name: reddit_clone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.5
  firebase_storage: ^11.6.7
  cloud_firestore: ^4.15.6
  firebase_auth: ^4.17.6
  google_sign_in: ^6.2.1
  flutter_riverpod: ^2.4.10
  fpdart: ^1.1.0
  routemaster: ^1.0.1
  dotted_border: ^2.1.0
  file_picker: ^6.1.1
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  any_link_preview: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/google.png
    - assets/images/loginEmote.png
    - assets/images/logo.png
    - assets/images/awards/


  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf


