// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKTS08v0trCAYblax-VqTkb0hie5NwXJg',
    appId: '1:471472368912:web:dd73ee86c8b998f37f4995',
    messagingSenderId: '471472368912',
    projectId: 'reddit-clone-8b3c3',
    authDomain: 'reddit-clone-8b3c3.firebaseapp.com',
    storageBucket: 'reddit-clone-8b3c3.appspot.com',
    measurementId: 'G-2YQBMNKBVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhbK2jwQZWrU7zMaJ9UXPURit3YTL9OVM',
    appId: '1:471472368912:android:d7ad4a207fa826ec7f4995',
    messagingSenderId: '471472368912',
    projectId: 'reddit-clone-8b3c3',
    storageBucket: 'reddit-clone-8b3c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-mDGtWQqtCB4g8x3kht57ACy5bqW-eic',
    appId: '1:471472368912:ios:9f467ab0450f55d67f4995',
    messagingSenderId: '471472368912',
    projectId: 'reddit-clone-8b3c3',
    storageBucket: 'reddit-clone-8b3c3.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-mDGtWQqtCB4g8x3kht57ACy5bqW-eic',
    appId: '1:471472368912:ios:d0a94b6ae5a5091e7f4995',
    messagingSenderId: '471472368912',
    projectId: 'reddit-clone-8b3c3',
    storageBucket: 'reddit-clone-8b3c3.appspot.com',
    iosBundleId: 'com.example.redditClone.RunnerTests',
  );
}
